FROM ubuntu

ADD https://github.com/Ensaodocker/Reverse/archive/refs/heads/main.zip . 

RUN apt-get update && apt-get install -y netcat &&  \
    apt-get install -y unzip && \
    apt-get install -y vim 
